spring:
  application:
    name: online-exam-system
  datasource:
    url: jdbc:mysql://localhost:3755/online_exam_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:  # 这里改为 mybatis-plus
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yourcompany.examsystem.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 30m

logging:
  level:
    com.yourcompany.examsystem: DEBUG
    com.yourcompany.examsystem.mapper: DEBUG
